name: Backup Supabase Database

on:
  schedule:
    - cron: '0 2 */3 * *' # Cada 3 días a las 2:00 AM UTC
  workflow_dispatch: # También poder correrlo manualmente

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Backup database
      env:
        HOST: ${{ secrets.SUPABASE_DB_HOST }}
        DB: ${{ secrets.SUPABASE_DB_NAME }}
        USER: ${{ secrets.SUPABASE_DB_USER }}
        PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        PORT: ${{ secrets.SUPABASE_DB_PORT }}
      run: |
        export PGPASSWORD=$PASSWORD
        pg_dump --host=$HOST --port=$PORT --username=$USER --format=custom --file=backup_$(date +'%Y-%m-%d').dump $DB

    - name: Upload backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: db-backup
        path: backup_*.dump
